name: Build Native Images
on:
  release:
    types: [published]
jobs:
  Build-Native-Images:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Image Build Step
      working-directory: ./compiler
      run: |
        GRAALVM_JAVA_HOME="$( ${GITHUB_WORKSPACE}/.github/workflows/env-setup )" ./release
        mv native-fpp-*.tar.gz "${GITHUB_WORKSPACE}"
    - name: Publish Release Binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ${GITHUB_WORKSPACE}/.github/workflows/publish native-fpp-*.tar.gz
